name             'chefconf2015_demoapp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chefconf2015_demoapp'
long_description 'Installs/Configures chefconf2015_demoapp'
version          '0.1.0'
